language: go
go: 
    - 1.2
    - 1.3
    - 1.4
    - release
    - tip

install:
    - go get github.com/tools/godep
    - go get github.com/stretchr/testify/assert

script:
    - godep go test ./...

services:
    - mongodb
